version: '3.8'

services:
  # Django Application
  web:
    build: .
    container_name: sklad_web
    restart: always
    volumes:
      # Statik va Media fayllar uchun
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      # MUHIM: SQLite bazasi o'chib ketmasligi uchun uni server bilan bog'laymiz
      # Agar loyihangizda db.sqlite3 fayli bo'lmasa, uni bo'sh holatda yaratib oling
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      # Faqat kerakli bo'lsa qoldiring, lekin settings.py da DEBUG=True qattiq yozilgan.
      # Settings.py bu yerdagi o'zgaruvchilarni o'qimaydi, lekin xavfsizlik uchun yozib qo'ydim.
      - DEBUG=True
      - SECRET_KEY=django-insecure-ebbz@ipv_0xexs7=k=)f9uu0gw4aaw3w@-7orvmlc#eubjo+7c
      - ALLOWED_HOSTS=*
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 4 config.wsgi:application"
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: sklad_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: