version: '3.8'

services:
  # 1. Django Application
  web:
    build: .
    container_name: sklad_web
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-ebbz@ipv_0xexs7=k=)f9uu0gw4aaw3w@-7orvmlc#eubjo+7c
      - ALLOWED_HOSTS=bekendchi.uz,www.bekendchi.uz,89.116.27.54
      # HTTPS uchun bu juda muhim, bo'lmasa Admin panelga kirolmaysiz:
      - CSRF_TRUSTED_ORIGINS=https://bekendchi.uz,https://www.bekendchi.uz
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"

  # 2. Nginx (HTTPS va Proxy)
  nginx:
    image: nginx:alpine
    container_name: sklad_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      # --- ASOSIY O'ZGARISH SHU YERDA ---
      # Biz yaratgan papkani Nginx ichiga ulaymiz:
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web

  # Certbot (hozircha shart emas, lekin keyinchalik yangilash uchun turaversin)
  certbot:
    image: certbot/certbot
    container_name: sklad_certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  static_volume:
  media_volume:
  certbot-conf:
  certbot-www: